if(typeof Math.imul == "undefined" || (Math.imul(0xffffffff,5) == 0)) {
    Math.imul = function (a, b) {
        var ah  = (a >>> 16) & 0xffff;
        var al = a & 0xffff;
        var bh  = (b >>> 16) & 0xffff;
        var bl = b & 0xffff;
        // the shift by 0 fixes the sign on the high part
        // the final |0 converts the unsigned value into a signed value
        return ((al * bl) + (((ah * bl + al * bh) << 16) >>> 0)|0);
    }
}


/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
            ;function e(a,b){return null!==a&&b in a?a[b]:void 0};function g(a){const b=a.length;if(0<b){const d=Array(b);for(let c=0;c<b;c++)d[c]=a[c];return d}return[]};var h={},k={};if("undefined"===typeof h||"undefined"===typeof k||"undefined"===typeof l)var l={};if("undefined"===typeof h||"undefined"===typeof k||"undefined"===typeof m)var m=null;if("undefined"===typeof h||"undefined"===typeof k||"undefined"===typeof p)var p=null;if("undefined"===typeof h||"undefined"===typeof k||"undefined"===typeof q)var q=null;function r(a){return null!=a&&!1!==a}
var t="undefined"!==typeof Math&&"undefined"!==typeof Math.imul?function(a,b){return Math.imul(a,b)}:function(a,b){var d=a&65535,c=b&65535;return d*c+((a>>>16&65535)*c+d*(b>>>16&65535)<<16>>>0)|0};function u(a){a=t(a|0,-862048943);a=0^(t(a<<15|a>>>-15,461845907)|0);a=(t(a<<13|a>>>-13,5)+-430675100|0)^0;a=t(a^a>>>16,-2048144789);t(a^a>>>13,-1028477387)}u(1);u(0);if("undefined"===typeof h||"undefined"===typeof k||"undefined"===typeof v)var v=null;
"undefined"!==typeof console&&(m=function(){var a=arguments;return console.log.apply(console,g.call(null,a))},p=function(){var a=arguments;return console.error.apply(console,g.call(null,a))});if("undefined"===typeof h||"undefined"===typeof k||"undefined"===typeof w)var w=function(){throw Error("cljs.core/*eval* not bound");};var x=["clojure","haskell","latex","lisp","julia"];function y(a,b){return document.querySelectorAll(a).forEach(b)}function A(a){return new Promise(function(b,d){var c=document.createElement("script");c.src=a;c.async=!1;c.onload=b;c.onerror=d;return document.head.appendChild(c)})}function B(){var a=document.createElement("link");a.rel="stylesheet";a.href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css";document.head.appendChild(a)}var C=document.documentElement;
function D(){return"dark"===C.getAttribute("data-theme")?"dark":"light"}function E(a){var b=e.call(null,window,"REMARK42");return r(b)?e.call(null,b,"changeTheme").call(b,a):null}function F(a,b){C.setAttribute("data-theme",a);if(r(b))try{localStorage.setItem("theme",a)}catch(c){console.warn("theme choice not saved",c)}var d=["Switch to ","dark"===a?"light":"dark"," theme"].join("");y(".theme-toggle",function(c){c.setAttribute("aria-label",d);return c.setAttribute("title",d)});return E(a)}
function G(){return F("dark"===D()?"light":"dark",!0)}function H(a){try{var b=localStorage.getItem("theme")}catch(d){b=null}return r(b)?null:F(r(a.matches)?"dark":"light",!1)}function I(){y(".theme-toggle",function(a){return a.addEventListener("click",G)});r(window.matchMedia)&&window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change",H);F(D(),!1)}
function J(){function a(f){c.toggle("menu-open",f);return d.setAttribute("aria-expanded",r(f)?"true":"false")}var b=document.querySelector(".sidebar"),d=document.querySelector(".menu-toggle"),c=null==b?null:b.classList;r(r(b)?d:b)&&(d.addEventListener("click",function(){var f=c.contains("menu-open");return a(null==f?!0:!1===f?!0:!1)}),document.addEventListener("keydown",function(f){f="Escape"===f.key;return r(f?c.contains("menu-open"):f)?(a(!1),d.focus()):null}))}
function K(a){return A(["https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/",a,".min.js"].join(""))}function L(){var a=e.call(null,window,"hljs");e.call(null,a,"configure").call(a,{ignoreUnescapedHTML:!0});return y("pre code",function(b){return e.call(null,a,"highlightElement").call(a,b)})}
function M(){r(document.querySelector("pre code"))&&A("https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js").then(function(){return Promise.all(x.map(K))}).then(L).catch(function(a){return console.warn("highlight.js failed to load",a)})}var N=RegExp("\\$\\$|\\\\\\(|\\\\\\[|\\\\begin\\{");function O(a){return{left:["\\begin{",a,"}"].join(""),right:["\\end{",a,"}"].join(""),display:!0}}
function P(){var a=document.querySelector(".prose");r(a)&&r(N.test(a.textContent))&&(B(),A("https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js").then(function(){return A("https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js")}).then(function(){return e.call(null,window,"renderMathInElement").call(window,a,{delimiters:[{left:"$$",right:"$$",display:!0},{left:"\\[",right:"\\]",display:!0},{left:"\\(",right:"\\)",display:!1}].concat("equation equation* align align* gather gather*".split(" ").map(O)),
ignoredTags:"script noscript style textarea pre code".split(" "),throwOnError:!1})}).catch(function(b){return console.warn("KaTeX failed to load",b)}))}function Q(a){return a.reduce(function(b,d){var c=document.getElementById(d.getAttribute("href").slice(1));return r(r(c)?120>c.getBoundingClientRect().top:c)?d.getAttribute("href").slice(1):b},null)}
function R(a,b,d){return a.forEach(function(c){return c.getAttribute("href").slice(1)===b?(c.setAttribute("aria-current","true"),r(d)?c.scrollIntoView({block:"nearest"}):null):c.removeAttribute("aria-current")})}function S(a,b){return r(b)?a.setAttribute("open",""):a.removeAttribute("open")}
function T(){var a=document.querySelector(".outline");if(r(a)){var b=a.querySelector("details"),d=Array.from(a.querySelectorAll("a")),c=window.matchMedia("(min-width: 80rem)"),f={current:null,queued:!1},z=function(){f.queued=!1;var n=Q(d);if(n===e.call(null,f,"current"))return null;f.current=n;return R(d,n,c.matches)};S(b,c.matches);c.addEventListener("change",function(n){return S(b,n.matches)});window.addEventListener("scroll",function(){if(r(e.call(null,f,"queued")))return null;f.queued=!0;return requestAnimationFrame(z)},
{passive:!0});z()}}function U(a){return{host:e.call(null,a,"host"),site_id:e.call(null,a,"siteId"),url:e.call(null,a,"url"),locale:e.call(null,a,"locale"),theme:D(),components:["embed"],no_footer:!0}}function V(){var a=document.querySelector("#remark42[data-host]");if(r(a)){a=U(a.dataset);var b=e.call(null,a,"host");window.remark_config=a;return A([b,"/web/embed.js"].join("")).catch(function(d){return console.warn("Remark42 failed to load",d)})}return null}
function W(){I();J();T();M();P();return V()}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",W):W();